include:
  remote: 'https://gitlab.com/ebarkie/gitlab-ci/raw/master/go.yml'

cache:
  paths:
    - version.go

stages:
  - setup
  - test
  - build

build:erx:
  extends: .build
  variables:
    BIN: 1x-proxy-erx
    GOOS: linux
    GARCH: mipsle

build:erl:
  extends: .build
  variables:
    BIN: 1x-proxy-erl
    GOOS: linux
    GARCH: mips64
