language: go
go:
  - 1.13.x
env:
  global:
    - GO111MODULE=on
  matrix:
    - ARCH=mipsle OS=linux BIN=1x-proxy-erx
    - ARCH=mips64 OS=linux BIN=1x-proxy-erl RUN_TESTS=true
install:
  - go mod download
  - go generate
script:
  - if [ "$RUN_TESTS" == true ]; then
      go test -race -v ./...;
    fi
  - GOARCH=$ARCH GOOS=$OS go build -o build/$BIN
deploy:
  provider: releases
  api_key:
    secure: NLSBw3u2Y6JGbJmY/sD7sYJI2Y8kvCY6or73kWZTaEY8MKyqfwJQgP5boGERnNye1J5SSzRaLZXK/dLX52/9n6GQZTnMvwWZHgQVoWWZ5RBCy6nozIRTFsh996X0eyTMx4Xx9vZnZXqZ1KDz4UiitOYNGC9dkBTShvajcwUijVABWFv3XRvstzwuqtyqV4KuHCGFV7jelsF7kItnXjct3CyjLhzwt+bHO+uO4lAFdz+UM7Nh/HNSLwSVbm7xZgwUwy7USuSLvsVKiSC7kt8Je5Lwar25kyH/kXVwuTH9rfPUFKOrBNqiM2nVM//RT9F22gvn4Ozh2T0LNZpkN0OeH4cCV20jisFXKVuetDnsg+c8aq9jjdX+lRMgKVkFspiNbZpabsV9//ASSQ0oXThlLCVok/QPD3OKHsSPz6XIbboX7DHH2AJMtyow9MSCWhBVtkKT/Hvy99bu4RckcGZ9KigN2G/RJz2VR9fhPZfg4zSPKUg2BtG7pJAevktPpo52hHajUyMObvLyi4HEvSAb9yeLhFd1vLPYtvR2cpW3IqFJ/uYqyKlC0Yw7tvNS1lChGKFna5Oo2Q4sVRz0QqIHm7CXo1BtF/OoeL/lyi9qv/hai3D0PwYmpSoxFpcDjzj/KqLAXOEArBVbhnVAJK93huqxtIVwOkjJsZGEFUKTfXo=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
