language: go
go:
  - 1.11.x
env:
  global:
    - GO111MODULE=on
  matrix:
    - ARCH=mipsle BIN=1x-proxy-erx
    - ARCH=mips64 BIN=1x-proxy-erl RUN_TESTS=true
before_install:
  - go generate
install:
  - go mod download
script:
  - if [ "$RUN_TESTS" == true ]; then
      go test -race -v ./...;
    fi
  - GOOS=linux GARCH=$ARCH go build -o build/$BIN
